console.log(typeof v);
var v;
console.log(typeof v);
v = "1";
console.log(typeof v);
v = 2;
console.log(typeof v);
v = true;
console.log(typeof v);
v = {};
console.log(typeof v);
v = Symbol();
console.log(typeof v);
v = null;
console.log(typeof v);
v = function () { };
console.log(typeof v);
v = [1, 2, 3];
console.log(typeof v);